{{ with $clusterIssuer := .Values.clusterIssuer}}
{{ if $clusterIssuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{$clusterIssuer.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{$clusterIssuer.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            solverName: stackit
            groupName: acme.stackit.de
            config:
              projectId: {{$clusterIssuer.projectID }}
              authTokenSecretNamespace: {{$.Release.Namespace}}
{{- end }}
{{- end }}