{{ with $clusterIssuer := .Values.clusterIssuer}}
{{ if $clusterIssuer.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{$.Release.Name}}
data:
  auth-token: {{$clusterIssuer.authToken}}
{{- end }}
{{- end }}